services:
    # UI Tests
    tests-ui:
        build: .
        image: cypress-automation
        container_name: cypress-ui-tests
        volumes:
            - ./allure-results:/app/allure-results
            - ./cypress/screenshots:/app/cypress/screenshots
            - ./cypress/videos:/app/cypress/videos
        env_file:
            - .env.dev
        command: npm run test:ui-dev

    # API Tests
    tests-api:
        image: cypress-automation
        container_name: cypress-api-tests
        volumes:
            - ./allure-results:/app/allure-results
            - ./cypress/screenshots:/app/cypress/screenshots
            - ./cypress/videos:/app/cypress/videos
        env_file:
            - .env.api
        command: npm run test:api

    # Generate report
    report:
        image: cypress-automation
        container_name: allure-report-generator
        volumes:
            - ./allure-results:/app/allure-results
            - ./allure-report:/app/allure-report
        command: npm run test:report

    # Allure Server
    serve:
        image: nginx:alpine
        volumes:
            - ./allure-report:/usr/share/nginx/html:ro
        ports:
            - '5050:80'
